name: deploy-github-pages
on:
  push:
    branches:
      - main  # 监控主分支的更新

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          curl -sSL https://github.com/rust-lang/mdBook/releases/latest/download/mdbook-linux-x86_64.tar.gz | tar -xz
          mv mdbook /usr/local/bin/mdbook
          chmod +x /usr/local/bin/mdbook

      - name: Build mdBook
        run: mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          force_orphan: true  # 强制创建无历史的 gh-pages 分支

