name: deploy-github-pages
on:
  push:
    branches:
      - main  # 监控主分支的更新

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup mdBook
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-mdbook@v1.2.0
        with:
          mdbook-version: '0.4.5'

      - name: Build site
        if: ${{ github.ref == 'refs/heads/main' }}
        working-directory: .
        run: mdbook build
      - name: Move HTML files to root
        run: |
          mv ./book/html/* ./book/
          rm -r ./book/html  # 删除空的 html 目录

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          force_orphan: true  # 强制创建无历史的 gh-pages 分支

